services:
  - type: web
    name: presentwallah-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: PEXELS_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: presentwallah-db
          property: connectionString
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 60

databases:
  - name: presentwallah-db
    databaseName: presentwallah
    user: presentwallah
